package com.vanhy.model;

// default package
// Generated Dec 6, 2018 3:02:25 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Author generated by hbm2java
 */
public class Author implements java.io.Serializable {

	private Integer id;
	private String nameAuthor;
	private List books = new ArrayList(0);

	public Author() {
	}

	public Author(String nameAuthor) {
		this.nameAuthor = nameAuthor;
	}

	public Author(String nameAuthor, List books) {
		this.nameAuthor = nameAuthor;
		this.books = books;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNameAuthor() {
		return this.nameAuthor;
	}

	public void setNameAuthor(String nameAuthor) {
		this.nameAuthor = nameAuthor;
	}

	public List<Book> getBooks() {
		return this.books;
	}

	public void setBooks(List books) {
		this.books = books;
	}

}
