package com.vanhy.model;

// default package
// Generated Dec 6, 2018 3:02:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Borrow generated by hbm2java
 */
public class Borrow implements java.io.Serializable {

	private Integer id;
	private Book book;
	private Reader reader;
	private Date borrowDate;
	private byte state;

	public Borrow() {
	}

	public Borrow(Book book, Reader reader, Date borrowDate, byte state) {
		this.book = book;
		this.reader = reader;
		this.borrowDate = borrowDate;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public Reader getReader() {
		return this.reader;
	}

	public void setReader(Reader reader) {
		this.reader = reader;
	}

	public Date getBorrowDate() {
		return this.borrowDate;
	}

	public void setBorrowDate(Date borrowDate) {
		this.borrowDate = borrowDate;
	}

	public byte getState() {
		return this.state;
	}

	public void setState(byte state) {
		this.state = state;
	}

}
