package com.vanhy.model;

// default package
// Generated Dec 6, 2018 3:02:25 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Reader generated by hbm2java
 */
public class Reader implements java.io.Serializable {

	private Integer id;
	private String name;
	private List borrows = new ArrayList(0);

	public Reader() {
	}

	public Reader(String name) {
		this.name = name;
	}

	public Reader(String name, List borrows) {
		this.name = name;
		this.borrows = borrows;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List getBorrows() {
		return this.borrows;
	}

	public void setBorrows(List borrows) {
		this.borrows = borrows;
	}

}
